postman-tests:
  stage: test
  image: 
    name: postman/newman:alpine
    entrypoint: [""]
  script: 
    - cd backend
    - newman --version
    - newman run UpdatedCollection.postman_collection.json
